### ISSUE TITLE
Installation fail on macOS

### ISSUE THREAD

**Issue by romainbh** [piMoll/SEILAPLAN#3]
Install QGIS 3.22.10 (also tested with 3.22.1) on macOS 10.15 and 13. Then install Seilaplan: can't load extension.

On different computers, different messages:
_____
ImportError: dlopen(/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so, 0x0002): Library not loaded: /opt/X11/lib/libxcb.1.dylib   Referenced from: /Applications/QGIS-LTR 2.app/Contents/Resources/python/site-packages/pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so   Reason: tried: '/opt/X11/lib/libxcb.1.dylib' (no such file), '/usr/local/lib/libxcb.1.dylib' (no such file), '/usr/lib/libxcb.1.dylib' (no such file) 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/aymericanthamatten/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/__init__.py", line 36, in classFactory
    from .seilaplanPlugin import SeilaplanPlugin
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/aymericanthamatten/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/seilaplanPlugin.py", line 56, in 
    from .gui.seilaplanPluginDialog import SeilaplanPluginDialog
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/aymericanthamatten/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/gui/seilaplanPluginDialog.py", line 46, in 
    from .profileDialog import ProfileDialog
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/aymericanthamatten/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/gui/profileDialog.py", line 33, in 
    from .profilePlot import ProfilePlot
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/aymericanthamatten/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/gui/profilePlot.py", line 27, in 
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/backends/backend_qt5agg.py", line 10, in 
    from .backend_agg import FigureCanvasAgg
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/backends/backend_agg.py", line 35, in 
    from PIL import Image
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/Image.py", line 94, in 
    from . import _imaging as core
  File "/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dlopen(/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so, 0x0002): Library not loaded: /opt/X11/lib/libxcb.1.dylib
  Referenced from: /Applications/QGIS-LTR 2.app/Contents/Resources/python/site-packages/pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so
  Reason: tried: '/opt/X11/lib/libxcb.1.dylib' (no such file), '/usr/local/lib/libxcb.1.dylib' (no such file), '/usr/lib/libxcb.1.dylib' (no such file)

Version de Python : 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
Version de QGIS : 3.22.5-Białowieża Białowieża, 2a0a86f142 
Chemin Python :
•	/Users/aymericanthamatten/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/lib
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python
•	/Users/aymericanthamatten/Library/Application Support/QGIS/QGIS3/profiles/default/python
•	/Users/aymericanthamatten/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/../Resources/python/plugins
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/lib-dynload
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python38.zip
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR 2.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Users/aymericanthamatten/Library/Application Support/QGIS/QGIS3/profiles/default/python
_____

ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so, 2): Library not loaded: /opt/X11/lib/libxcb.1.dylib   Referenced from: /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so   Reason: image not found 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/sylvainchabloz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/__init__.py", line 36, in classFactory
    from .seilaplanPlugin import SeilaplanPlugin
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/sylvainchabloz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/seilaplanPlugin.py", line 56, in 
    from .gui.seilaplanPluginDialog import SeilaplanPluginDialog
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/sylvainchabloz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/gui/seilaplanPluginDialog.py", line 46, in 
    from .profileDialog import ProfileDialog
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/sylvainchabloz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/gui/profileDialog.py", line 33, in 
    from .profilePlot import ProfilePlot
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/sylvainchabloz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/gui/profilePlot.py", line 27, in 
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/backends/backend_qt5agg.py", line 10, in 
    from .backend_agg import FigureCanvasAgg
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/backends/backend_agg.py", line 35, in 
    from PIL import Image
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/Image.py", line 94, in 
    from . import _imaging as core
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so, 2): Library not loaded: /opt/X11/lib/libxcb.1.dylib
  Referenced from: /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so
  Reason: image not found

Version de Python : 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
Version de QGIS : 3.22.10-Białowieża Białowieża, 44701d6dd7 
Chemin Python :
•	/Users/sylvainchabloz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SEILAPLAN/lib
•	/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
•	/Users/sylvainchabloz/Library/Application Support/QGIS/QGIS3/profiles/default/python
•	/Users/sylvainchabloz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
•	/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/lib-dynload
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python38.zip
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
•	/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Users/sylvainchabloz/Library/Application Support/QGIS/QGIS3/profiles/default/python
_____

Tested on 3 Mac computers

**Comment by piMoll** [comment]
Hello!

Sorry to hear that you have issues with Seilaplan.

Some months ago, we had a user with a very similar issue and call stack as yours. Back then, we were not able to help because our macOS experience is very limited. Luckily, the user asked someone at OpenGIS and they found a solution: They recommended to install XQuartz from [https://www.xquartz.org/](https://www.xquartz.org/ ).  That solved the dependency issue for the user. Maybe this could help you as well?

**Comment by romainbh** [comment]
Hello ;-)

Thanks @piMoll for this solution, it works! We've tested it on 3 macOS computers and yet Seilaplan works well.
